name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      # - name: Install Pandoc
      #   run: | # install pandoc
      #     curl -s -L https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-linux-amd64.tar.gz | tar xvzf - -C $RUNNER_TOOL_CACHE/
      # - name: Hexo Generate
      #   run: | # add pandoc to PATH
      #     export PATH="$PATH:$RUNNER_TOOL_CACHE/pandoc-2.9.2/bin"
      #     rm -f .yarnclean
      #     yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
      #     rm -rf ./public
      #     npm run clean
      #     npm run build
      
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
